#!/usr/bin/env lua

package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

local sbar = require("sketchybar")
sbar.begin_config()
require("init")
require("left")
require("right")
require("middle")
sbar.hotload(true)
sbar.end_config()
sbar.event_loop()

-- Configuración para múltiples monitores
sbar.default {
    padding_left = 10,
    padding_right = 10,
    height = 28,
    y_offset = 0,
    top = true,
    align = "center",
    display = "all"
}

sbar.hotload(true)
sbar.end_config()
sbar.event_loop()

