#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color=0xffc29df1 #0xffe2e2e3
	inactive_color=0xff182c2c #0xff414550  #0xffc29df1
	#background_color=0x302c2e34
)

borders "${options[@]}"
