# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
	{ on = [ "j" ], run = [ "plugin --sync arrow --args=1"],  desc = "Move selection downwards, or wrap." },
	{ on = [ "k" ], run = [ "plugin --sync arrow --args=-1"], desc = "Move selection upwards, or wrap." },
	{ on = [ "l" ], run = [ "plugin smart-enter --sync", "escape --visual --select" ], desc = "Enter the child directory, or open file." },
	{ on = [ "n" ], run = "plugin smart-enter --sync --args='detatch'", desc = "Open in new window." },
    { on = [ "=" ], run = """
        shell 'printf "Mode Bits: "; read ans; chmod $ans "$@"' --block --confirm
    """, desc = "chmod" },
    { on = [ "T" ], run = [ "plugin --sync hide-preview"], desc = "Hide or show preview" },
    { on = [ "X" ], run = [ "plugin --sync max-preview"], desc = "Maximize or retore preview" },
    { on = [ "c", "m" ], run = [ "plugin chmod"], desc = "Chmod on selected files" },
    { on = [ "F" ], run = [ "plugin smart-filter"], desc = "Smart filter" },
    { on = [ "f" ], run = [ "plugin jump-to-char"], desc = "Jump to char" },
    { on = [ "R" ], run = [ "plugin rsync --args='tuxadm@sabaext'"], desc = "Copiando archivo via rsync a sabaext" }
]


#[[manager.prepend_keymap]]
#on   = [ "l" ]
#run  = "plugin --sync smart-enter"
#desc = "Enter the child directory, or open the file"

