after-login-command = []

# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  # JankyBorders has a built-in detection of already running process,
  # so it won't be run twice on AeroSpace restart
  'exec-and-forget borders style=round width=5.0 hidpi=off active_color=0xc0e2e2e3 inactive_color=0xc02c2e34 background_color=0x302c2e34',
  #'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
  # Sketchybar has a built-in detection of already running process,
  # so it won't be run twice on AeroSpace restart
  'exec-and-forget sketchybar --reload',
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE EMPTY_WORKSPACES=$(aerospace list-workspaces --monitor focused --empty)',
]

# Normalizations. See: https://nikitabobko.giaedrthub.io/AeroSpace/guide.html#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Start AeroSpace at login
start-at-login = true

# Controla el espaciado (en píxeles) entre los paneles (ventanas) cuando se utiliza el modo de diseño de acordeón
accordion-padding = 20

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse lazily follows any focus (window or workspace)
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 35
#outer.top = [ {monitor.'^built-in retina display$' = 10}, 50 ] 
outer.right = 6

[workspace-to-monitor-force-assignment]
1 = 'Built-in Retina Display'
2 = 'Built-in Retina Display'
3 = 'Built-in Retina Display'
4 = 'DELL P2419H'
5 = 'DELL P2419H'
6 = 'DELL P2419H'
7 = 'LG FHD'
8 = 'LG FHD'
9 = 'LG FHD'
#10 = 'LG FHD'
#11 = 'LG FHD'

[mode.main.binding]

ctrl-enter = 'exec-and-forget open -n /Applications/WezTerm.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
#alt-s = 'layout v_accordion' # 'layout stacking' in i3
#alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-slash = 'layout tiles horizontal vertical'     # Cambiar al diseño de mosaicos y cambia la orientación del diseño si ya está en el diseño de mosaicos ('layout toggle split' in i3)
alt-comma = 'layout accordion horizontal vertical'

cmd-shift-v = 'layout v_tiles' # Cambie el diseño (layout) y la orientación de los mosaicos de una sola vez
cmd-shift-h = 'layout h_tiles'

#alt-shift-q = 'close --quit-if-last-window'

# Para poder usar estas opciones hay que desactivar enable-normalization-flatten-containers 
# https://nikitabobko.github.io/AeroSpace/commands#split
#alt-v = 'split horizontal'
#alt-x = 'split vertical'

alt-f = 'fullscreen'
alt-shift-f = 'macos-native-fullscreen'

alt-cmd-t = 'layout floating tiling' # 'floating toggle' in i3

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-h = 'focus left'
ctrl-alt-j = 'focus down'
ctrl-alt-k = 'focus up'
ctrl-alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'
ctrl-alt-6 = 'workspace 6'
ctrl-alt-7 = 'workspace 7'
ctrl-alt-8 = 'workspace 8'
ctrl-alt-9 = 'workspace 9'
#ctrl-alt-0 = 'workspace 0'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
#alt-shift-0 = 'move-node-to-workspace 0'

# https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-right = 'workspace next'
alt-left = 'workspace prev'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-ctrl-p = 'move-workspace-to-monitor --wrap-around prev'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-s = 'mode service'
alt-r = 'mode resize'

# Desactiva el acceso directo "ocultar aplicación"
cmd-h = []
cmd-alt-h = [] # Disable "hide others"

alt-shift-c = 'reload-config'
ctrl-alt-shift-s = [
  'reload-config',
  'exec-and-forget sketchybar --reload',
  'mode main',
]

alt-shift-left = ['join-with left', 'mode main']
alt-shift-down = ['join-with down', 'mode main']
alt-shift-up = ['join-with up', 'mode main']
alt-shift-right = ['join-with right', 'mode main']

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2

f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'


[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'VNC'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.keepassxc.keepassxc'
run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.daisydiskapp.DaisyDiskStandAlone'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.microsoft.rdc.macos'
run = ['layout floating', 'move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = 'zoom'
run = ['layout floating', 'move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'Pantalla en Pantalla'
run = ['layout floating']
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
if.window-title-regex-substring = 'Picture-in-Picture'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.corecode.MacUpdater'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.linguee.DeepLCopyTranslator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'layout floating'
